version: "3"

volumes:
  auth-postgres:
    external: true
  ticket-postgres:
    external: true

services:
  auth-postgres-0:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - auth-postgres:/var/lib/postgresql/hw-auth/data
  ticket-postgres-0:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ticket-postgres:/var/lib/postgresql/hw-ticket/data
    ports:
      - "9001:5432"
  redis-server:
    restart: on-failure
    image: "redis"
  node:
    restart: on-failure
    links:
      - ticket-postgres-0
      - go
      - bank
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
  go:
    restart: on-failure
    links:
      - auth-postgres-0
      - redis-server
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
  bank:
    restart: on-failure
    build:
      context: ./Bank_back
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
  hw-nginx:
    restart: on-failure
    links:
      - node
      - go
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
